apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-producer-microservice
  name: udaconnect-location-producer-microservice
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 5005
      nodePort: 30004
  selector:
    service: udaconnect-location-producer-microservice
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-producer-microservice
  name: udaconnect-location-producer-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-producer-microservice
  template:
    metadata:
      labels:
        service: udaconnect-location-producer-microservice
    spec:
      containers:
        - image: fahadfiaz00/udaconnect-location-producer-microservice:latest
          name: udaconnect-location-producer-microservice
          imagePullPolicy: Always
      restartPolicy: Always